### ISSUE TITLE
API Bearer Auth plugin (I am sorry i dont know where to ask)

### ISSUE THREAD

**Issue by chrisgate** [michielvaneerd/easyexercise#1]
It will nice if this plugin can return:
"token_expires" and "refreshtoken_expires"

and if the token can be parse by http://jwt.ms/ and http://jwt.io/

The plugin is so cool and i am excited about it.

Thanks in anticipations

**Comment by michielvaneerd** [comment]
Hi, I don't know if you're interested anymore, but I released a new version with JWT token support. For other questions regarding this plugin, please go to: https://wordpress.org/support/plugin/api-bearer-auth
